title:              "Eunji World"
email:              "eunjihong.3698@gmail.com"
description:        "Bienvenue mes amis!"
author:             "Eunji HONG"
baseurl:            ""
url:                "https://eunzihong.github.io"

# Social Profiles
#twitter_username:   SBootstrap
github_username:    eunzihong
facebook_username:  Eunji Hong
#linkedin_username:

# Add your google-analytics ID here to activate google analytics
#google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
